project:
  type: website

website:
  title: "Ying Cao | Data Scientist"  # 网站标题
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: index.qmd         
      - text: "Resume"
        href: resume.pdf 
      - icon: github
        href: https://github.com/Inori124
      - icon: linkedin
        href: https://linkedin.com/in/你的链接

format:
  html:
    theme: cosmo          # 主题，推荐 cosmo, flatly, 或 darkly
    css: styles.css
    toc: true             # 开启侧边目录