project:
  type: website
  output-dir: docs

website:
  title: "Ying Cao | Portfolio"  # 网站标题
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd         
      - text: "Articles"
        href: portfolio.qmd
      - text: "Resume"
        href: resume.qmd 
      - icon: github
        href: https://github.com/Inori124
      - icon: linkedin
        href: https://linkedin.com/in/你的链接

format:
  html:
    theme: cosmo          # 主题，推荐 cosmo, flatly, 或 darkly
    css: styles.css
    toc: true             # 开启侧边目录